{% set version = "0.0.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggfun
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggfun_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggfun/ggfun_{{ version }}.tar.gz
  sha256: 59989ed260fcc71cd95487cf3493113a2d8a47d273d9a2f3e5e842609620511b

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-rlang
  run:
    - r-base
    - r-ggplot2
    - r-rlang

test:
  commands:
    - $R -e "library('ggfun')"           # [not win]
    - "\"%R%\" -e \"library('ggfun')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggfun
  license: Artistic-2.0
  summary: Useful functions to edit 'ggplot' object (e.g., setting fonts for theme and layers, adding rounded rectangle as background for each of the legends).
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
